# Generated by Django 5.2 on 2025-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('grains_pulses', 'Grains & Pulses'), ('dairy_products', 'Dairy Products'), ('fertilizers', 'Fertilizers'), ('fishery', 'Fishery'), ('flowers', 'Flowers'), ('nursery_plants', 'Nursery Plants'), ('poultry_products', 'Poultry Products'), ('spices', 'Spices'), ('nuts_dry_fruits', 'Nuts & Dry Fruits'), ('oils_ghee', 'Oils & Ghee'), ('manure', 'Manure'), ('coffee_tea', 'Coffee & Tea')], max_length=50),
        ),
    ]
