# Generated by Django 5.1.1 on 2025-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='afa85c', max_length=6),
        ),
    ]
